[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gdt"
version = "0.1.0"
description = "Gene Dictionary Tool - Bioinformatics package"
authors = [
    {name = "Breno Dupin", email = "breno.dupin@gmail.com"},
    {name = "Matheus Sanita Lima", email = "msanital@uwo.ca"},
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "pandas"
]

[project.urls]
Homepage = "https://--placeholder--"
Repository = "https://gitlab.com/brenodupin/gdt"

[project.scripts]
geneDict = "gdt.cli:cli_run"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools.package-dir]
"" = "src"