line-length = 88
target-version = "py312"

include = ["src/**.py", "notebooks/**.ipynb"]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # pyflakes
    "C90", # mccabe complexity
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "D",   # pydocstyle (if you want docstring compliance)
]
ignore = [
    "D203",  # Keep D211 (no blank line before class)
    "D213",  # Keep D212 (summary on first line)
    "N816",
    "N815"
]

mccabe.max-complexity = 16

[lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"notebooks/*.ipynb" = ["E501", "F401", "E402", "W292", "W291", "W293", "E302", "E305", "F821"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false