name: CI
on:
  push:
    paths:
      - 'src/**'
      - 'notebooks/**'
  pull_request:
    paths:
      - 'src/**'
      - 'notebooks/**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
      
      - name: Install dependencies (with dev)
        run: uv sync --group dev
      
      - name: Lint with ruff
        id: lint
        run: uv run ruff check src/ notebooks/
        continue-on-error: true
      
      - name: Format with black
        id: format
        run: uv run black --check src/ notebooks/
        continue-on-error: true
      
      - name: Type check with mypy
        id: typecheck
        run: uv run mypy --strict src/
        continue-on-error: true
      
      - name: Check if any step failed
        run: |
          if [[ "${{ steps.lint.outcome }}" == "failure" ]] || \
             [[ "${{ steps.format.outcome }}" == "failure" ]] || \
             [[ "${{ steps.typecheck.outcome }}" == "failure" ]]; then
            echo "One or more checks failed:"
            echo "  - Lint: ${{ steps.lint.outcome }}"
            echo "  - Format: ${{ steps.format.outcome }}"
            echo "  - Type check: ${{ steps.typecheck.outcome }}"
            exit 1
          fi